
import file_lists
from Scripts.include.package import *
from math import ceil
from fault_injector_do import generate_links_dictionary, generate_fault_injection_do

def write_do_file(program_argv, net_file_name, net_tb_file_name, wave_do_file_name, logging):
    """
    Generates a simulate.do file for running Modelsim.
        program_argv:       program arguments
        net_file_name:      file name for the generated network
        net_tb_file_name:   file name for the generated network
        wave_do_file_name:  file name for the generated wave.do file
        logging:            logging file
    """

    logging.info("Generating simulation.do")

    flow_control_type = HANDSHAKING_SUFFIX

    do_file = open(SIMUL_DIR + "/" + SIMUL_DO_SCRIPT, 'w')

    do_file.write("#########################################\n")
    do_file.write("# Copyright (C) 2016 Project Bonfire    #\n")
    do_file.write("#                                       #\n")
    do_file.write("# This file is automatically generated! #\n")
    do_file.write("#             DO NOT EDIT!              #\n")
    do_file.write("#########################################\n\n")

    do_file.write("vlib work\n\n")

    do_file.write("# Include files and compile them\n")


    ##### Simulation files #####

   
    # Handshaking based flow control

        # With checkers
    if program_argv['add_checkers']:
        for file in file_lists.HS_Arbiter_one_hot_with_checkers:
            do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type + CHECKERS_DIR \
                + "/Arbiter_one_hot_with_checkers/"+file+"\"\n")

        for file in file_lists.HS_Arbiter_one_hot_with_checkers:
            do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type + CHECKERS_DIR \
                + "/FIFO_one_hot_with_checkers/"+file+"\"\n")

        for file in file_lists.HS_LBDR_with_checkers:
            do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type + CHECKERS_DIR \
                + "/LBDR_with_checkers/"+file+"\"\n")

        do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type \
            + "/RTL/xbar.vhd\"\n")

    else:
        # No checkers
        for file in file_lists.handshaking_files:
            do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type \
                + "/RTL/"+file+"\"\n")


        # Add a network interface
        if program_argv['add_NI'] != -1:
            do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type \
                + "/RTL/NI.vhd\"\n")
            do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type \
                + "/RTL/NI_channel.vhd\"\n")

        # Add parity checking
        if program_argv['add_parity']:
            do_file.write("vcom \"" + FAULT_MANAGEMENT_RTL_DIR \
                + "/Error_Detection_Correction/ParityChecker.vhd\"\n")

            do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type \
                + "/RTL/Router_32_bit_handshaking_parity.vhd\"\n")
        else:
            if program_argv['add_checkers']:
                do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type \
                    + "/RTL/Router_32_bit_handshaking_with_full_set_of_checkers.vhd\"\n")
            else:
                do_file.write("vcom \"" + ROUTER_RTL_DIR + "/" + flow_control_type \
                    + "/RTL/Router_32_bit_handshaking.vhd\"\n")

    # End of handshaking based flow control

    # Include file for the testbench
  
    do_file.write("vcom \"" + TEST_DIR + "/" + flow_control_type \
        + "/TB_Package_32_bit_" + flow_control_type + ".vhd\"\n")

    # Generated network files
    do_file.write("vcom \"" +  net_file_name + "\"\n")
    do_file.write("vcom \"" +  net_tb_file_name + "\"\n\n")

    #### Simulation control ####

    do_file.write("# Start the simulation\n")
    do_file.write("vsim work.tb_network_" \
        + str(program_argv['network_dime']) + "x" + str(program_argv['network_dime']) + "\n\n")

    do_file.write("# Draw waves\n")
    do_file.write("do " + wave_do_file_name + "\n")

    do_file.write("# Run the simulation\n")

    if program_argv['add_FI']:

        links = generate_links_dictionary(program_argv['network_dime'], program_argv['sim'])

        generate_fault_injection_do(SIMUL_DIR, program_argv['sim'], program_argv['end'], links)
        do_file.write("do fault_inject.do")
    else:

        if program_argv['sim'] == -1 and program_argv['end'] == -1:
            do_file.write("run 15000 ns\n")

        elif program_argv['sim'] != -1 and program_argv['end'] == -1:

            do_file.write("run " + str(int(ceil(program_argv['sim'] * 1.5))) + " ns\n")

        else:
            do_file.write("run " + str(program_argv['end']) + " ns\n")

    if program_argv['lat']:
        do_file.write("\n# Exit Modelsim after simulation\n")
        do_file.write("exit\n")
    do_file.close()
    logging.info("finished writing do file...")

    return None
